name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check -- --color=always
      - run: |
          cargo clippy --all-features --all-targets --color=always \
            -- -D warnings
        env:
          RUSTFLAGS: "-Dwarnings"

  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-deadlinks
      - run: cargo deadlinks
      - run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: -Dwarnings
