name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  timezones-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        tz: ["ACST-9:30", "EST4", "UTC0", "Asia/Katmandu"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --all-features

  timezones-other:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        tz: ["ACST-9:30", "EST4", "UTC0", "Asia/Katmandu"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --all-features
